config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: {
    sessions: 'suppliers/sessions',
    passwords: 'suppliers/passwords',
    registrations: 'suppliers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root 'companies#top'

  resources :users, only: :show
  resources :profiles, only: %i[new create edit update]
  resources :careers, only: %i[new create edit update destroy]

  resources :chats, only: %i[index new create show] do
    resources :messages, only: %i[new create]
  end

  namespace :supplier do
    resources :supplier_question_answers, only: %i[new create]
    resources :image_other_companies, only: %i[new create]
    resources :supplier_notifications, only: %i[index]
    resources :chats, only: %i[index new create show] do
      resources :messages, only: %i[new create]
    end

    resources :companies, only: %i[index create show edit update] do
      collection do
        get 'first_step'
        get 'second_step'
        get 'third_step'
        get 'fourth_step'
        get 'fifth_step'
        get 'sixth_step'
        get 'double_check'
      end

      member do
        get 'company_details'
        get 'ingredients_edit'
        get 'ingredients_update'
      end
    end
  end

  resources :user_question_answers, only: [:show] do
    collection do
      get 'question_description'
      get 'choice_questions'
      post 'answer_choice_questions'
      get 'scale_questions'
      post 'scale_choice_questions'
      get 'thinker'
      get 'pasi'
      get 'hamo'
      get 'ima'
      get 'revel'
      get 'pro'
    end
  end

  resources :companies, only: %i[index show] do
    resource :favorites, only: %i[show create destroy]
    resource :entries, only: %i[new create destroy]
    collection do
      get 'top'
      get 'search'
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :supplier_question_answers, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :image_other_companies, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :user_notifications, dependent: :destroy
  has_many :supplier_notifications, dependent: :destroy
  has_one_attached :company_image

  validates :company_name, presence: true
  validates :company_image, presence: true

  PERSONALITY_TYPE_SCORE_BASE = {
    thinker: 1,
    pasi: 2,
    hamo: 3,
    ima: 4,
    revel: 5,
    pro: 6
  }

  def build_personality_hash
    supplier_answers = supplier_question_answers
    hash = { 'hamo' => 0, 'pasi' => 0, 'revel' => 0, 'thinker' => 0, 'ima' => 0, 'pro' => 0 }
    supplier_answers.each do |answer|
      hash[answer.personality_type] += answer.point
    end
    hash
  end

  def calc_personality_score
    place = 100_000
    score = 0
    build_personality_hash.sort_by { |_, v| -v }.to_h.each do |personality_type, _score|
      score += place * Supplier::PERSONALITY_TYPE_SCORE_BASE[personality_type.to_sym]
      place /= 10
    end
    score
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  impressionist actions: [:show]

  def top; end

  def index
    @company_topimage = Company.find(1)
    @company_images = Company.where.not(id: 1)
    if current_user
      @companies = Company.joins(:supplier).order("abs(suppliers.personality_score - #{current_user.personality_score})").page(params[:page]).per(5)
    else
      @companies = Company.all.page(params[:page]).per(5)
    end  
  end

  def show
    @company = Company.find(params[:id])
    @ingredients = JSON.parse(@company.ingredients)
    @other_images = @company.supplier.image_other_companies
    impressionist(@company, nil, unique: [:session_hash])
  end

  def search
    @keyword = params[:keyword]
    @area = params[:area]
    @genre = params[:genre]
    @companies = Company.all
    @companies = @companies.keyword(params[:keyword]) if params[:keyword] != ''
    @companies = @companies.area(params[:area]) if params[:area] != '0'
    @companies = @companies.genre(params[:genre]) if params[:genre] != ''
  end
end

app/controllers/supplier/chats_controller.rb
class Supplier::ChatsController < ApplicationController
  before_action :authenticate_supplier!

  def index; end

  def show
    @chat_room = Chat.find(params[:id])
    @user_name = @chat_room.user.family_name
    @messages = @chat_room.messages
    @message = Message.new
    @chat_room.supplier.supplier_notifications.where(user_id: @chat_room.user, notification_type: 'message',
                                                     checked_at: nil).update(checked_at: Time.current)
  end

  def new
    @chat = Chat.new
    has_chat_user_ids = current_supplier.chats.pluck(:user_id)
    @entries = current_supplier.entries.where.not(user_id: has_chat_user_ids)
  end

  def create
    @chat = Chat.new(chat_params)
    @entry = current_supplier.entries
    if @chat.save
      @chat.supplier.supplier_notifications.where(user_id: @chat.user_id, notification_type: 'entry',
                                                  checked_at: nil).update(checked_at: Time.current)
      redirect_to supplier_chats_path
    else
      render 'new'
    end
  end

  def chat_params
    params.require(:chat).permit(:user_id).merge(supplier_id: current_supplier.id, latest_message_time: Time.current)
  end
end

app/controllers/supplier/companies_controller.rb
class Supplier::CompaniesController < ApplicationController
  before_action :authenticate_supplier!, except: %i[first_step]
  before_action :set_company_find, only: %i[edit update company_details ingredients_edit ingredients_update]
  before_action :set_company_new, only: %i[second_step third_step fourth_step fifth_step sixth_step double_check]
  before_action :move_to_index, only: %i[company_details edit update]

  def first_step; end

  def second_step; end

  def third_step
    session[:prefecture_id] = company_params[:prefecture_id]
    session['founding_date(1i)'] = params[:company]['founding_date(1i)']
    session['founding_date(2i)'] = params[:company]['founding_date(2i)']
    session['founding_date(3i)'] = params[:company]['founding_date(3i)']
    session[:phone_number] = company_params[:phone_number]
    session[:company_url] = company_params[:company_url]
  end

  def fourth_step
    session[:company_content] = company_params[:company_content]
  end

  def fifth_step
    session[:company_purpose] = company_params[:company_purpose]
  end

  def sixth_step
    session[:company_environment] = company_params[:company_environment]
  end

  def double_check
    session[:ingredients] = company_params[:ingredients]
    @check = Company.new(
      prefecture_id: session[:prefecture_id],
      founding_date: "#{session['founding_date(1i)']}-#{session['founding_date(2i)']}-#{session['founding_date(3i)']}",
      phone_number: session[:phone_number],
      company_url: session[:company_url],
      company_content: session[:company_content],
      company_purpose: session[:company_purpose],
      company_environment: session[:company_environment],
      ingredients: session[:ingredients]
    )
  end

  def create
    @company = Company.new(
      prefecture_id: session[:prefecture_id],
      founding_date: "#{session['founding_date(1i)']}-#{session['founding_date(2i)']}-#{session['founding_date(3i)']}",
      phone_number: session[:phone_number],
      company_url: session[:company_url],
      company_content: session[:company_content],
      company_purpose: session[:company_purpose],
      company_environment: session[:company_environment],
      ingredients: session[:ingredients],
      supplier_id: current_supplier.id
    )
    if @company.save
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'sixth_step'
    end
  end

  # 企業側のユーザーページ
  def company_details
    @favorites = Favorite.where(company_id: current_supplier.id).count
    @entries = Entry.where(supplier_id: current_supplier.id).count
    @ingredients = JSON.parse(@company.ingredients)
    @other_images = @company.supplier.image_other_companies

    @supplier_answer = current_supplier.supplier_question_answers
    @total = { 'hamo' => 0, 'pasi' => 0, 'revel' => 0, 'thinker' => 0, 'ima' => 0, 'pro' => 0 }
    @supplier_answer.each do |answer|
      @total[answer.personality_type] += answer.point
    end
  end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'edit'
    end
  end

  def ingredients_edit; end

  def ingredients_update
    if @company.update_attributes(ingredients_params)
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'ingredients_edit'
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :prefecture_id,
      :founding_date,
      :phone_number,
      :company_url,
      :company_content,
      :company_purpose,
      :company_environment,
      ingredients: []
    ).merge(supplier_id: current_supplier.id)
  end

  def ingredients_params
    params.require(:company).permit(ingredients: [])
  end

  def set_company_new
    @company = Company.new
  end

  def set_company_find
    @company = Company.find(params[:id])
  end

  def move_to_index
    return redirect_to root_path if current_supplier.id != @company.supplier.id
  end
end

app/controllers/supplier/image_other_companies_controller.rb
class Supplier::ImageOtherCompaniesController < ApplicationController
  def new
    @image = ImageOtherCompany.new
  end

  def create
    @image = ImageOtherCompany.new(image_other_company_params)
    if @image.save
      redirect_to company_details_supplier_company_path(current_supplier)
    else
      render 'new'
    end
  end

  private

  def image_other_company_params
    params.require(:image_other_company).permit(:image_other_company).merge(supplier_id: current_supplier.id)
  end
end

app/controllers/supplier/messages_controller.rb
class Supplier::MessagesController < ApplicationController
  def create
    if current_user
      @sent_person = current_user.family_name
    elsif current_supplier
      @sent_person = current_supplier.company_name
    end
    @chat_room = Chat.find(params[:chat_id])
    @message = @chat_room.messages.new(message_params)
    if @message.save
      @chat_room.update(latest_message: @message.content, latest_message_time: Time.current)
      @chat_room.user.user_notifications.create(supplier: current_supplier)
    end
    redirect_to supplier_chat_path(@chat_room)
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(sent_person: @sent_person)
  end
end

app/controllers/supplier/supplier_notifications_controller.rb
class Supplier::SupplierNotificationsController < ApplicationController
  def index; end
end

app/controllers/supplier/supplier_question_answers_controller.rb
class Supplier::SupplierQuestionAnswersController < ApplicationController
  def new
    @questions = SupplierQuestion.order(:sort_order)
  end

  def create
    @questions = SupplierQuestion.order(:sort_order)
    ActiveRecord::Base.transaction do
      @questions.each do |question|
        question.supplier_question_options.each do |option|
          raise ActiveRecord::Rollback unless params[option.id.to_s].present?

          SupplierQuestionAnswer.create!(supplier_id: current_supplier.id,
                                         supplier_question_id: option.supplier_question_id, personality_type: option.personality_type, point: params[option.id.to_s])
        end
      end
      current_supplier.personality_score = current_supplier.calc_personality_score
      current_supplier.save!
      redirect_to company_details_supplier_company_path(current_supplier.id)
    rescue StandardError
      render :new
    end
  end
end

# current_supplier.personality_score = current_supplier.calc_personality_score
# current_supplier.save!

app/controllers/suppliers/confirmations_controller.rb
# frozen_string_literal: true

class Suppliers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/suppliers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Suppliers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/suppliers/passwords_controller.rb
# frozen_string_literal: true

class Suppliers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/suppliers/registrations_controller.rb
# frozen_string_literal: true

class Suppliers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    second_step_supplier_companies_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/suppliers/sessions_controller.rb
# frozen_string_literal: true

class Suppliers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(_resource)
    company_details_supplier_company_path(current_supplier.id)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/suppliers/unlocks_controller.rb
# frozen_string_literal: true

class Suppliers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def third_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社のサービスは、どのような実績をあげていますか？
    ・プロダクトの強みとして、自慢できるポイントはなんですか？
    ・あなたの会社は、これからどのような展開をしていきますか？
    EOS
  end

  def fourth_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社が理想として掲げる理念はなんですか？
    ・企業活動を通して果たすべき使命（ミッション）はありますか？
    ・どのような志を持つ方を仲間に入れたいですか？
    EOS
  end

  def fifth_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社では、どのような行動指針を大切にしていますか？
    ・チーム、職場はどのような雰囲気ですか？
    ・企業文化を支える、ユニークな制度はありますか？
    EOS
  end
end

app/views/supplier/companies/_chat.html.erb
<div class="d-flex flex-column ms-5">
    <%= link_to(new_supplier_chat_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-5 bg-primary bg-gradient")  do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <span class="text-white  ms-2">初めての人とチャットをする</span>
    <% end %>

    <%= link_to(supplier_chats_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-5 bg-primary bg-gradient")  do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <span class="text-white  ms-2">すでにメッセージをやりとりしている人とチャットする</span>
    <% end %>
</div>

app/views/supplier/companies/_setting.html.erb
<div class="d-flex flex-column ms-5">
    <%= link_to(edit_supplier_company_path(current_supplier), class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-4 bg-primary bg-gradient")  do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <span class="text-white  ms-2">企業情報を編集する</span>
    <% end %>

    <%= link_to(ingredients_edit_supplier_company_path(current_supplier), class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-4 bg-primary bg-gradient")  do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <span class="text-white  ms-2">求める職種を変更する</span>
    <% end %>

    <%= link_to(new_supplier_image_other_company_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-4 bg-primary bg-gradient")  do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
      <span class="text-white  ms-2">企業画像を追加する</span>
    <% end %>
</div>

app/views/supplier/companies/double_check.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を登録する 〜</h1>
    <%= form_with model: @company, url: supplier_companies_path, method: :post, local: true do |f|%>
      <div class="fs-1 text-secondary mb-4">最終確認</div>

      <dl class="row ms-5">
        <dd class="col-sm-3 mb-4 text-secondary">会社名</dd>
        <dt class="col-sm-9 mb-4"><%= current_supplier.company_name %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">所在地</dd>
        <dt class="col-sm-9 mb-4"><%= @check.prefecture.name %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">創立</dd>
        <dt class="col-sm-9 mb-4"><%="#{@check.founding_date.year}年#{@check.founding_date.month}月" %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">電話番号</dd>
        <dt class="col-sm-9 mb-4"><%= @check.phone_number %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">会社HP</dd>
        <dt class="col-sm-9 mb-4"><%= @check.company_url %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">事業内容</dd>
        <dt class="col-sm-9 mb-4"><%= @check.company_content %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">事業目的</dd>
        <dt class="col-sm-9 mb-4"><%= @check.company_purpose %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">働く環境</dd>
        <dt class="col-sm-9 mb-4"><%= @check.company_environment %></dt>

        <dd class="col-sm-3 mb-4 text-secondary">職種</dd>
        <dt class="col-sm-9 mb-4"><%= @check.ingredients %></dt>

      </dl>


      <%= f.submit "登録する" ,class:"btn btn-primary float-end mb-5" %>
    <% end %>
  </div>
</div>

app/views/supplier/companies/edit.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を編集する 〜</h1>
    <%= form_with model: @company, url: supplier_company_path, local: true do |f|%>

      <div class="container">
        <div class="row ">
        
          <div class="col-3 d-flex align-items-center ">
            <div class="form-floating mb-1 location">
              <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select_box_company border-primary rounded-pill px-2", id:"item-prefecture"})%>
            </div>
          </div>

          <div class="col-8 ">
            <div class="px-4 pt-2">
                <dl class="row">
                    <dd class="col-sm-4 mt-4 ps-5">創立年月</dd>
                    <dd class="col-sm-7 mt-3">
                        <div class='input-birth-wrap'>
                            <%= raw sprintf(
                                  f.date_select(
                                    :founding_date,
                                    class:'select-birth',
                                    id:"birth-date",
                                    use_month_numbers: true,
                                    discard_day: true,
                                    prompt:'--',
                                    start_year: 1980,
                                    end_year: (Time.now.year),
                                    date_separator: '%s'),
                                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
                        </div>
                    </dd>
                </dl>
            </div>
          </div>

        </div>
      </div>

      <div class="p-3">
        <div class="form-floating">
          <%= f.text_field :phone_number , class:"form-control border border-primary rounded-pill" , id:"floatingInput" , placeholder:"name@example.com" %>
          <label for="floatingInput">電話番号</label>
        </div>
      </div>

      <div class="p-3">
        <div class="form-floating">
          <%= f.text_field :company_url, class:"form-control border border-primary rounded-pill" , id:"floatingInput" , placeholder:"name@example.com" %>
          <label for="floatingInput">会社HP</label>
        </div>
      </div>

      <div class="fs-6 mt-5">あなたの会社の事業内容について編集する</div>
      <%= f.text_area :company_content, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:third_step_placeholder%>

      <div class="fs-6 mt-5">あなたの事業の目的について編集する</div>
      <%= f.text_area :company_purpose, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:fourth_step_placeholder %>

      <div class="fs-6 mt-5">チームの文化や働く環境について編集する</div>
      <%= f.text_area :company_environment, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:fifth_step_placeholder %>

      <%= f.submit "企業情報を編集する" ,class:"btn btn-primary float-end my-5" %>
    <% end %>
  </div>
</div>

app/views/supplier/companies/first_step.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を掲載する 〜</h1>

    <div class="d-flex flex-column">
        <%= link_to(new_supplier_registration_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-5 bg-primary bg-gradient")  do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
          </svg>
          <span class="text-white  ms-2">初めて掲載される企業様はこちら</span>
        <% end %>

        <%= link_to(new_supplier_session_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image my-5 bg-primary bg-gradient")  do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
          </svg>
          <span class="text-white  ms-2">すでに掲載していただいている企業様はこちら</span>
        <% end %>
    </div>

  </div>
</div>