config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: {
    sessions: 'suppliers/sessions',
    passwords: 'suppliers/passwords',
    registrations: 'suppliers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root 'companies#top'

  resources :users, only: :show
  resources :profiles, only: %i[new create edit update]
  resources :careers, only: %i[new create edit update destroy]

  resources :chats, only: %i[index new create show] do
    resources :messages, only: %i[new create]
  end

  namespace :supplier do
    resources :supplier_question_answers, only: %i[new create]
    resources :image_other_companies, only: %i[new create]
    resources :supplier_notifications, only: %i[index]
    resources :chats, only: %i[index new create show] do
      resources :messages, only: %i[new create]
    end

    resources :companies, only: %i[index create show edit update] do
      collection do
        get 'first_step'
        get 'second_step'
        get 'third_step'
        get 'fourth_step'
        get 'fifth_step'
        get 'sixth_step'
        get 'double_check'
      end

      member do
        get 'company_details'
        get 'ingredients_edit'
        get 'ingredients_update'
      end
    end
  end

  resources :user_question_answers, only: [:show] do
    collection do
      get 'question_description'
      get 'choice_questions'
      post 'answer_choice_questions'
      get 'scale_questions'
      post 'scale_choice_questions'
      get 'thinker'
      get 'pasi'
      get 'hamo'
      get 'ima'
      get 'revel'
      get 'pro'
    end
  end

  resources :companies, only: %i[index show] do
    resource :favorites, only: %i[show create destroy]
    resource :entries, only: %i[new create destroy]
    collection do
      get 'top'
      get 'search'
    end
  end
end

app/models/user_question_answer.rb
class UserQuestionAnswer < ApplicationRecord
  enum personarity_type: { hamo: 'hamo', thinker: 'thinker', pasi: 'pasi', revel: 'revel', ima: 'ima', pro: 'pro' }

  belongs_to :user
  belongs_to :question
  belongs_to :question_option, optional: true

  with_options presence: true, numericality: { other_than: 0 } do
    validates :point
  end
end

app/controllers/user_question_answers_controller.rb
class UserQuestionAnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[thinker pasi hamo ima revel pro]

  def choice_questions
    @questions = Question.choice.order(:sort_order)
  end

  def answer_choice_questions
    questions = Question.choice.order(:sort_order)
    questions.each do |question|
      option_id = params[question.id.to_s]
      question_option = QuestionOption.find(option_id)
      answer = current_user.user_question_answers.find_or_initialize_by(question_id: question.id)
      answer.question_option_id = question_option.id
      answer.personality_type = question_option.personality_type
      answer.point = question_option.point
      answer.save!
    end
    redirect_to scale_questions_user_question_answers_path
  end

  def scale_questions
    @questions = Question.scale.order(:sort_order)
  end

  def scale_choice_questions
    questions = Question.scale.order(:sort_order)
    questions.each do |question|
      point = params[question.id.to_s].to_i
      answer = current_user.user_question_answers.find_or_initialize_by(question_id: question.id)
      answer.personality_type = question.personality_type
      answer.point = point
      answer.save!
    end
    current_user.personality_score = current_user.calc_personality_score
    current_user.save!
    redirect_to user_question_answer_path(current_user)
  end

  def show
    answers = current_user.user_question_answers
    @total = current_user.build_personality_hash
  end

  def thinker; end

  def pasi; end

  def hamo; end

  def ima; end

  def revel; end

  def pro; end
end

app/helpers/user_question_answers_helper.rb
module UserQuestionAnswersHelper
end

app/views/user_question_answers/hamo.html.erb
<div class="personality_base">
  <h1 class="appname fs-1" >Work,LiveShift</h1>
  <h1 class="user_title mb-5 fs-6" >〜 パーソナリティ 〜</h1>
  <div class="hamo_name fw-lighte fs-3 mb-3">心情・思いやり</div>

  <div class="personality_descriptions">
    <div class="description_title text-secondary fs-4 my-4">◎性格の特徴</div>
    <div class="description_option hamo_option ps-5 my-4">
      “人間関係を大切にし、人の気持ちを優先します”<br>
      人の気持ちに敏感で、思いやりがあって、感受性が豊かな温かい心遣いができる人です。<br>
      自分のことよりも相手を優先し「与える」「はぐくむ」能力に長けており、包容力があります。<br>
      人間関係を重んじ、家族や友情、人の輪を大切にし、調和を作り出すことを得意とします。<br>
      あなたにとって重要なことは、自分も周りの人も心が安らぎ、居心地が良いと感じられることです。<br>
      他者の「喜び」「悲しみ」も自分ごとのように感じれる共感力を持っているため、<br>
      人の気持ちを非常に大切にする人です。<br>
    </div>

             <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎行動基準</div>
    <div class="description_option hamo_option ps-5 my-4">
        ”あなたが幸せに感じられるのは周りの人との良い人間関係が築けているときです”<br>
        人間関係第一のあなたにとって幸せとは、愛する家族や恋人、友人、<br>
        職場の仲間と思いやりを持ちながら良い人間関係を築けているときに幸せに感じる事が多いです。<br>
        逆に、大切な方との関係がうまくいっていない状況だと、<br>
        どれだけ仕事で成功を収めていたとしても、寂しさや不安を抱き続け、気持ちが沈んでしまいます。<br>
        自分を無条件で受け入れてくれる存在、環境に身を置くことが幸せに生きることにつながります。<br>
    </div>

               <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎仕事選びでのポイント</div>
    <div class="description_option hamo_option ps-5 my-4">
        人間関係第一のあなたにとって職場は第二の家族なような物です。<br>
        メンバーのみんなが仲良く働けている職場では自分の力を発揮しやすいでしょう。<br>
        逆に、どれだけ仕事にやりがいを感じていたり、給料が良かったとしても、<br>
        誰かが揉めていたり、険悪な雰囲気の中ではストレスを感じてしまうことが多くなってきます。<br>
        自分自身にとっても居心地が良いと感じられる場所を選ぶことが重要です。<br>
        仕事以外でも家族や友人、恋人との時間を大切にする必要があるため<br>
        プライベートが充実できる環境が良いでしょう。<br>
        <br>
        また、”人に喜んでもらいたい”,”困っている人を助けたい”という純粋な気持ちが<br>
        仕事への動機となることも多いので、そのような想いを持って働ける仕事、職場では<br>
        モチベーション高く仕事に取り組めるでしょう。<br>
    </div>

                <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎向いてる職業</div>
    <div class="description_option hamo_option ps-5 my-4">
        人を育む・人に喜んでもらう・人を助けてあげたいという仕事は向いています。<br>
        例）接客業／受付／看護師／介護士／販売／サービス業全般／保育士／学校の先生 etc...<br>
    </div>

  </div>
</div>

<div class="container footer border-top">
      <div class="ps-5 fs-3">他のパーソナリティについても見る</div>
      <div class="mt-5">
          <div class="d-flex justify-content-around ">
            <%= link_to '思考・論理', thinker_user_question_answers_path, class: "thinker_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '意見・価値観', pasi_user_question_answers_path, class: "pasi_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '心情・思いやり', hamo_user_question_answers_path, class: "hamo_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '内省・想像', ima_user_question_answers_path, class: "ima_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '反応・ユーモア', revel_user_question_answers_path, class: "revel_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '行動・魅力', pro_user_question_answers_path, class: "pro_tag border rounded-pill p-3 text-decoration-none text-dark" %>
          </div>
      </div>
</div>

<%# 戻るボタン %>
<div class="d-flex justify-content-center">
  <button class="user_btn border border-white rounded-pill bg-gradient "> 
  <% if user_signed_in? %>
    <%= link_to 'ユーザー画面に戻る', user_path(current_user.id), class: "text-decoration-none text-white" %>
  <% elsif supplier_signed_in? %>
    <%= link_to '企業詳細画面に戻る', company_details_supplier_company_path(current_supplier.id), class: "text-decoration-none text-white" %>
  <% end %>
  </button>
</div>

app/views/user_question_answers/ima.html.erb
<div class="personality_base">
  <h1 class="appname fs-1" >Work,LiveShift</h1>
  <h1 class="user_title mb-5 fs-6" >〜 パーソナリティ 〜</h1>
  <div class="ima_name fw-lighte fs-3 mb-3">内省・想像</div>

  <div class="personality_descriptions">
    <div class="description_title text-secondary fs-4 my-4">◎性格の特徴</div>
    <div class="description_option ima_option ps-5 my-4">
      あなたは何よりも想像力に秀でており、物事を思慮深く見つめ、振り返って思いを巡らせる能力に優れています。<br>
      豊かな想像力を活用し、”もう一人の自分”という視点で客観的に物事を見ることや<br>
      過去に起こった出来事が、今まさに目の前で起こっているかのようにありありと想像できるため<br>
      他の人が見落としてしまうような出来事も冷静に指摘する事ができます。<br>
      口数が少なく、比較的物静かな方が多いですが、<br>
      それは自分自身の内面が非常に豊かであるため外に対して発する言葉を必要としないためです。<br>
    </div>

             <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎行動基準</div>
    <div class="description_option ima_option ps-5 my-4">
        豊かな想像力を持ち、内省的なあなたにとって幸せとは平穏で変化の少ない安定した人生です。<br>
        誰にも邪魔されない時間と空間をしっかりと確保することが重要であり、<br>
        どれだけ親しい人と居たとしても、自分だけの一人の時間がないとストレスに感じてしまいます。<br>
        また、心が平穏でいられる状態が、自分の心が満たされている状態であり<br>
        今現在、自分が何をやらなければいけないのか？が曖昧な状況ではストレスを感じやすいです。<br>
        そのため、職場や周りの人からの明確な指示を受けることを望み、<br>
        やらないといけないと事が明確な状況では自分自身の力を発揮しやすいです。<br>
    </div>

               <hr align="center" >


    <div class="description_title text-secondary fs-4 my-4">◎仕事選びでのポイント</div>
    <div class="description_option ima_option ps-5 my-4">
        自発的に行動をすることよりも、明確な指示を受けた方が仕事がしやすいです。<br>
        明確な指示があれば、他の人が苦痛に思うような単調な作業も苦ではありません。<br>
        また、手先が器用な方も多く、細かさが要求される仕事に対しても黙々と作業を続ける事ができます。<br>
        時間に焦らされたり、他の人に干渉される事が少ないような、<br>
        自分のペースで仕事をこなすことで能率や生産性が向上します。<br>
    </div>

                <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎向いてる職業</div>
    <div class="description_option ima_option ps-5 my-4">
        豊かな想像力を活かし、豊かな世界観を表現する仕事や<br>
        業務内容に対して明確に指示があり、自分の時間や空間が確保されている仕事が向いています。<br>
        例）作家／漫画家／映画監督／俳優／詩人／画家／プログラマー／エンジニア etc...<br>
    </div>

  </div>
</div>

<div class="container footer border-top">
      <div class="ps-5 fs-3">他のパーソナリティについても見る</div>
      <div class="mt-5">
          <div class="d-flex justify-content-around ">
            <%= link_to '思考・論理', thinker_user_question_answers_path, class: "thinker_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '意見・価値観', pasi_user_question_answers_path, class: "pasi_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '心情・思いやり', hamo_user_question_answers_path, class: "hamo_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '内省・想像', ima_user_question_answers_path, class: "ima_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '反応・ユーモア', revel_user_question_answers_path, class: "revel_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '行動・魅力', pro_user_question_answers_path, class: "pro_tag border rounded-pill p-3 text-decoration-none text-dark" %>
          </div>
      </div>
</div>

<%# 戻るボタン %>
<div class="d-flex justify-content-center">
  <button class="user_btn border border-white rounded-pill bg-gradient "> 
  <% if user_signed_in? %>
    <%= link_to 'ユーザー画面に戻る', user_path(current_user.id), class: "text-decoration-none text-white" %>
  <% elsif supplier_signed_in? %>
    <%= link_to '企業詳細画面に戻る', company_details_supplier_company_path(current_supplier.id), class: "text-decoration-none text-white" %>
  <% end %>
  </button>
</div>

app/views/user_question_answers/pasi.html.erb
<div class="personality_base">
  <h1 class="appname fs-1" >Work,LiveShift</h1>
  <h1 class="user_title mb-5 fs-6" >〜 パーソナリティ 〜</h1>
  <div class="pasi_name fw-lighte fs-3 mb-3">意見・価値観</div>

  <div class="personality_descriptions">
    <div class="description_title text-secondary fs-4 my-4">◎性格の特徴</div>
    <div class="description_option pasi_option ps-5 my-4">
      あなたは自分の中の価値基準に沿って行動し、一度自分で決めたことは簡単には放り投げない強さを持っています。<br>
      自分自身の信念に沿って行う行動が、仮に損をしてしまう結果であっても使命感を持って献身的に取り組みます。<br>
      物事に対しては信頼や信用を重んじているため、筋を通し、礼儀を重んじ、精神性を重要視しています。<br>
      このような志が周囲からも誠実な態度として評価されることも多いと思います。<br>
      また、自分の意見、信念、価値観、主義主張を人に伝える能力が高く、<br>
      物事の本質を見抜き判断や評価を下す能力にも長けています。<br>
      他にも、「自分自身を成長させていこう」という自己研鑽欲求が高く、ストイックな面も持っています。<br>
    </div>

             <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎行動基準</div>
    <div class="description_option pasi_option ps-5 my-4">
あなたにとっての幸せは、<br>
あなたにとって価値があると信じているものにとことん打ち込み、それに生涯を捧げることです。<br>
私利私欲をよりも”世のため人のため”になるような、自分の信念に沿って生きる。<br>
そのことで人から尊敬の念を持ってもらえることで幸せに感じます。<br>
また、自分の仕事や活動に誇りとプライドを持ち、納得のいくまで辛抱強く取り組み、<br>
その道を極めることを目指します。<br>
このように何事にも妥協しない、一生懸命取り組んでいる姿を自分自身や周りの人に評価してもらえると、<br>
「努力した甲斐があった」と心が満たされることがあると思います。<br>
自分自身の努力も重要ですが、他者の努力している姿にも影響を受けることがあり、<br>
テレビ番組ではドキュメンタリー番組を好む方も多いです。<br>
    </div>

               <hr align="center" >


    <div class="description_title text-secondary fs-4 my-4">◎仕事選びでのポイント</div>
    <div class="description_option pasi_option ps-5 my-4">
      損得や私利私欲よりも、自分自身の信念、社会貢献など世のため人のためになる仕事が適任です。<br>
      一度決めたことを簡単に投げ出さない性格から、粘り強さや献身的に打ち込むことが求められる仕事や、<br>
      自分の想いや意見を述べる能力から、人の上に立ってビジョンや理念を示し陣頭指揮を取るポジションで<br>
      働くことで自分自身の力を発揮しやすいです。<br>
      また、妥協は敵、安易な方向に流れることがなく、本質を見抜く目を持っていることから、<br>
      社内の議論などの本質的な問題を突き止めたりする業務も向いています。<br>
    </div>

                <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎向いてる職業</div>
    <div class="description_option pasi_option ps-5 my-4">
      その仕事に就くことで社会貢献を意識できる仕事や、粘り強い努力が求められる仕事が向いています。<br>
      例）警察官／消防士／自衛官／医師／職人／教師／政治家／ジャーナリスト／記者／弁護士 etc...<br>
    </div>

  </div>
</div>

<div class="container footer border-top">
      <div class="ps-5 fs-3">他のパーソナリティについても見る</div>
      <div class="mt-5">
          <div class="d-flex justify-content-around ">
            <%= link_to '思考・論理', thinker_user_question_answers_path, class: "thinker_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '意見・価値観', pasi_user_question_answers_path, class: "pasi_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '心情・思いやり', hamo_user_question_answers_path, class: "hamo_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '内省・想像', ima_user_question_answers_path, class: "ima_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '反応・ユーモア', revel_user_question_answers_path, class: "revel_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '行動・魅力', pro_user_question_answers_path, class: "pro_tag border rounded-pill p-3 text-decoration-none text-dark" %>
          </div>
      </div>
</div>

<%# 戻るボタン %>
<div class="d-flex justify-content-center">
  <button class="user_btn border border-white rounded-pill bg-gradient "> 
  <% if user_signed_in? %>
    <%= link_to 'ユーザー画面に戻る', user_path(current_user.id), class: "text-decoration-none text-white" %>
  <% elsif supplier_signed_in? %>
    <%= link_to '企業詳細画面に戻る', company_details_supplier_company_path(current_supplier.id), class: "text-decoration-none text-white" %>
  <% end %>
  </button>
</div>

app/views/user_question_answers/pro.html.erb
<div class="personality_base">
  <h1 class="appname fs-1" >Work,LiveShift</h1>
  <h1 class="user_title mb-5 fs-6" >〜 パーソナリティ 〜</h1>
  <div class="pro_name fw-lighte fs-3 mb-3">行動・魅力</div>

  <div class="personality_descriptions">
    <div class="description_title text-secondary fs-4 my-4">◎性格の特徴</div>
    <div class="description_option pro_option ps-5 my-4">
        物事を前進させる能力に秀で、他人を説得し行動させる力と<br>
        周りをどんどん引っ張ってリードしていく牽引力に優れています。<br>
        また、人を惹きつける魅力を持っており、男性も女性もすごく魅力的に見られる事が多いです。<br>
        普通の人では臆してしまうような逆境に強く、<br>
        競争心やチャレンジ精神を掻き立てられると燃えてくる方も多いです。<br>
        どのような状況にも順応し、魅力と行動力で周りを巻き込む強さを持っています。<br>
    </div>

             <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎行動基準</div>
    <div class="description_option pro_option ps-5 my-4">
        「幸せは自ら掴み取るもの。待っていても向こうからは来ない」というのがあなたの考え。<br>
        ”今がチャンス”と思ったら機を逃さず即行動。<br>
        リスクを恐れず、エネルギッシュに突き進んでいきます。<br>
        安定した人生よりもジェットコースターのような変化の多い人生を好み、<br>
        普通の人生では達成できないような大成功を求める方も多いです。<br>
        また、ターゲットやハードルが大きいほど、エネルギーが沸き力を発揮します。<br>
    </div>

               <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎仕事選びでのポイント</div>
    <div class="description_option pro_option ps-5 my-4">
        仕事は、取引上手で立ち回りがうまい営業、セールスに向いています。<br>
        決められたノルマをコツコツと計画を立てて地道にこなすよりも、<br>
        ”今がチャンス！”という時に、即行動を起こし大きな成果を得る事が多く、<br>
        成果に対してインセンティブなど報酬がすぐに手に入ることで達成感を感じる方が多いです。<br>
        <br>
        また、ほうぼうに飛び回って大きなプロジェクトを展開したり、<br>
        人生を左右するような新規事業の立ち上げを繰り消したりと、<br>
        一度成功を手にしても、現状に満足することなく動き続けることがあなたのエネルギーになってきます。<br>
    </div>

                <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎向いてる職業</div>
    <div class="description_option pro_option ps-5 my-4">
        普通の人では臆してしまうような仕事や、インセンティブの大きい仕事。<br>
        また、人からの注目が集まるような仕事は向いています。<br>
        例）セールス／モデル／起業家／不動産 etc...<br>
    </div>

  </div>
</div>

<div class="container footer border-top">
      <div class="ps-5 fs-3">他のパーソナリティについても見る</div>
      <div class="mt-5">
          <div class="d-flex justify-content-around ">
            <%= link_to '思考・論理', thinker_user_question_answers_path, class: "thinker_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '意見・価値観', pasi_user_question_answers_path, class: "pasi_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '心情・思いやり', hamo_user_question_answers_path, class: "hamo_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '内省・想像', ima_user_question_answers_path, class: "ima_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '反応・ユーモア', revel_user_question_answers_path, class: "revel_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '行動・魅力', pro_user_question_answers_path, class: "pro_tag border rounded-pill p-3 text-decoration-none text-dark" %>
          </div>
      </div>
</div>

<%# 戻るボタン %>
<div class="d-flex justify-content-center">
  <button class="user_btn border border-white rounded-pill bg-gradient "> 
  <% if user_signed_in? %>
    <%= link_to 'ユーザー画面に戻る', user_path(current_user.id), class: "text-decoration-none text-white" %>
  <% elsif supplier_signed_in? %>
    <%= link_to '企業詳細画面に戻る', company_details_supplier_company_path(current_supplier.id), class: "text-decoration-none text-white" %>
  <% end %>
  </button>
</div>

app/views/user_question_answers/question_description.html.erb
<div class="new_base">
  <div class="new_inbase">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 性格診断について 〜</h1>

   <%= render 'question_description' %>

  <%= link_to '性格診断へ進む', choice_questions_user_question_answers_path, class: "btn btn-primary float-end mb-5" %>
  </div>
</div>

app/views/user_question_answers/revel.html.erb
<div class="personality_base">
  <h1 class="appname fs-1" >Work,LiveShift</h1>
  <h1 class="user_title mb-5 fs-6" >〜 パーソナリティ 〜</h1>
  <div class="revel_name fw-lighte fs-3 mb-3">反応・ユーモア</div>

  <div class="personality_descriptions">
    <div class="description_title text-secondary fs-4 my-4">◎性格の特徴</div>
    <div class="description_option revel_option ps-5 my-4">
        あなたは天真爛漫な子供のようなピュアな心を持っています。<br>
        なにか行動を起こすときは、自分がしたい、楽しそうだからするのであって<br>
        誰かのためや、頭で考えた計画だからという理由ではありません。<br>
        ひらめき直感に優れ、既成概念、常識、習慣に囚われることなく<br>
        誰も思い付かないようなアイデアや発想を生み出す創造力に富んでいます。<br>
    </div>

             <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎行動基準</div>
    <div class="description_option revel_option ps-5 my-4">
        天真爛漫なあなたにとって何よりも大事なことは、”楽しい”かどうかです。<br>
        人生のスローガンは”楽しくてこそ人生！”と言えるぐらい、あなたの人生には楽しいことは重要です<br>
        現在の活動や、仕事、遊びなど全ての物事において<br>
        ”楽しい！”と思えているときは、エネルギッシュでパワフルに自分の力を発揮できます。<br>
        逆に、現在の活動が「楽しくない」「つまらない」「めんどくさい」となってしまうと<br>
        モチベーションが下がってきてしまうので、いかに”楽しむか！”をが人生の成功につながります。<br>
    </div>

               <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎仕事選びでのポイント</div>
    <div class="description_option revel_option ps-5 my-4">
          仕事選びで最も重要なことは自分な好きなことや、仕事が楽しいと思えるかどうかです。<br>
          きちっとした時間に決まった場所で決まった業務をこなす。<br>
          また、会社の規則やルールが多く自由があまり許されない環境だと自分の力が発揮しにくいでしょう。<br>
          それよりもフリーランスやフレックスタイム制が導入されていたり、<br>
          なんらかの遊びが許されている（音楽を聴きながら仕事をしても良いなど）環境では仕事を楽しみやすくなってきます。<br>
          また、何かを創作したり、デザインしたりなど、全く新しいものを生み出す創造力が<br>
          求められる職場だと自分自身の強みを発揮できます。<br>
    </div>

                <hr align="center" >

    <div class="description_title text-secondary fs-4 my-4">◎向いてる職業</div>
    <div class="description_option revel_option ps-5 my-4">
          ひらめき・創造性・発想力が求められる職業が向いています<br>
          例）デザイナー／カメラマン／コピーライター／お笑いタレント／漫画家／クリエイター etc...<br>
    </div>

  </div>
</div>

<div class="container footer border-top">
      <div class="ps-5 fs-3">他のパーソナリティについても見る</div>
      <div class="mt-5">
          <div class="d-flex justify-content-around ">
            <%= link_to '思考・論理', thinker_user_question_answers_path, class: "thinker_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '意見・価値観', pasi_user_question_answers_path, class: "pasi_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '心情・思いやり', hamo_user_question_answers_path, class: "hamo_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '内省・想像', ima_user_question_answers_path, class: "ima_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '反応・ユーモア', revel_user_question_answers_path, class: "revel_tag border rounded-pill p-3 text-decoration-none text-dark" %>
            <%= link_to '行動・魅力', pro_user_question_answers_path, class: "pro_tag border rounded-pill p-3 text-decoration-none text-dark" %>
          </div>
      </div>
</div>

<%# 戻るボタン %>
<div class="d-flex justify-content-center">
  <button class="user_btn border border-white rounded-pill bg-gradient "> 
  <% if user_signed_in? %>
    <%= link_to 'ユーザー画面に戻る', user_path(current_user.id), class: "text-decoration-none text-white" %>
  <% elsif supplier_signed_in? %>
    <%= link_to '企業詳細画面に戻る', company_details_supplier_company_path(current_supplier.id), class: "text-decoration-none text-white" %>
  <% end %>
  </button>
</div>