config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: {
    sessions: 'suppliers/sessions',
    passwords: 'suppliers/passwords',
    registrations: 'suppliers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root 'companies#top'

  resources :users, only: :show
  resources :profiles, only: %i[new create edit update]
  resources :careers, only: %i[new create edit update destroy]

  resources :chats, only: %i[index new create show] do
    resources :messages, only: %i[new create]
  end

  namespace :supplier do
    resources :supplier_question_answers, only: %i[new create]
    resources :image_other_companies, only: %i[new create]
    resources :supplier_notifications, only: %i[index]
    resources :chats, only: %i[index new create show] do
      resources :messages, only: %i[new create]
    end

    resources :companies, only: %i[index create show edit update] do
      collection do
        get 'first_step'
        get 'second_step'
        get 'third_step'
        get 'fourth_step'
        get 'fifth_step'
        get 'sixth_step'
        get 'double_check'
      end

      member do
        get 'company_details'
        get 'ingredients_edit'
        get 'ingredients_update'
      end
    end
  end

  resources :user_question_answers, only: [:show] do
    collection do
      get 'question_description'
      get 'choice_questions'
      post 'answer_choice_questions'
      get 'scale_questions'
      post 'scale_choice_questions'
      get 'thinker'
      get 'pasi'
      get 'hamo'
      get 'ima'
      get 'revel'
      get 'pro'
    end
  end

  resources :companies, only: %i[index show] do
    resource :favorites, only: %i[show create destroy]
    resource :entries, only: %i[new create destroy]
    collection do
      get 'top'
      get 'search'
    end
  end
end

app/views/shared/_footer.html.erb
<div class="container footer border-top">
  <div class="row ">
     <div class="navbar-brand">Work,LiveShift</div>
  </div>
</div>

app/views/shared/_header.html.erb
<%# 未ログイン時のヘッダー %>
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid" >
    <%= link_to 'Work,LiveShift', root_path, class: "navbar-brand" %>
    <div class="d-flex ">

      <%= link_to(new_user_session_path, class: "text-decoration-none")  do %>
        <div class="btn btn-outline-success d-flex justify-content-end d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-check-fill  text-primary " viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            </svg>
            <span class="text-primary  ms-2">ログイン</span>
        </div>
      <% end %>

      <%= link_to(new_user_registration_path, class: "text-decoration-none") do %>
        <div class="btn btn-outline-success d-flex justify-content-end d-flex align-items-center mx-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-plus-fill text-primary " viewBox="0 0 16 16">
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
            </svg>
            <span class="text-primary  ms-2">新規登録</span>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_header_signin.html.erb
<%# ログイン中のヘッダー %>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid" >
      <%= link_to 'Work,LiveShift', root_path, class: "navbar-brand mt-1" %>
          
    <%# ヘッダーのアイコン %>

    <div class="d-flex">
      <div class="d-flex align-items-center">

          <div class="balloonoya border-end border-1 border-dark">
              <%= link_to(companies_path) do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-building text-dark mx-3" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
                  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                </svg>
              <% end %>
            <span class="balloon text-center">企業一覧へ移動する</span>
          </div>


          <%# チャットのアイコン %>

          <div class="balloonoya">
              <%= link_to(chats_path) do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-chat-square-dots mx-3 text-dark" viewBox="0 0 16 16">
                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                </svg>
              <% end %>
            <span class="balloon text-center">チャット画面へ</span>
          </div>

        <%# すずのアイコン %>
          <div class="dropdown">
            <div class="btn" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-bell ms-2" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
              <% if @user_notifications.present? %>
                <span class="badge bg-danger">new</span>
              <% end %>
            </div>
            <ul class="dropdown-menu dropdown-menu-end ps-3" aria-labelledby="dropdownMenuButton">
            <% if @user_notifications.present? %>
              <% @user_notifications.each do |notification| %>
                <li><%= link_to "#{notification.supplier.company_name}からメッセージが届きました", chats_path, class: "dropdown-item me-4"%></li>
              <% end %>
            <% else %>
              <li><a class="dropdown-item me-3" href="#">現在通知はありません</a></li>
            <% end %>
            </ul>
          </div>

        <%# 人のアイコン %>
          <div class="balloonoya">
            <%= link_to(user_path(current_user.id))  do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle mx-3 text-dark" viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
              <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
              </svg>
            <% end %>
            <span class="balloon text-center">ユーザーページへ</span>
          </div>

            <%# ここからは右上のユーザーネームのドロップボタン %>
        <div class="dropdown">
            <button class="btn mx-2 px-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <%# （ ↪︎ idの「dropdown-toggle」を消すとドロップボックスの矢印が消える） %>
            
                <%# ユーザーネームと画像を表示させる %>
              <%= current_user.family_name%><%= image_tag current_user.image, class: 'rounded-circle ms-3', :size =>'55x55'%>
            </button>
                <%# ドロップボタンのリスト %>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
              <li><%= link_to 'お気に入りにした企業', company_favorites_path(current_user), class: "dropdown-item ms-2" %></li>
              <li><a class="dropdown-item ms-2" href="#">応募した企業</a></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: " dropdown-item btn btn-outline-success text-center ms-2" %></li>
            </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_header_supplier_signin.html.erb
<%# ログイン中のヘッダー %>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid" >
      <%= link_to 'Work,LiveShift', root_path, class: "navbar-brand mt-1" %>
          
    <%# ヘッダーのアイコン %>

    <div class="d-flex">
      <div class="d-flex align-items-center">

          <div class="balloonoya border-end border-1 border-dark">
              <%= link_to(company_path(current_supplier.companies.ids)) do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-building text-dark mx-3" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
                  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                </svg>
              <% end %>
            <span class="balloon text-center">掲載画面へ移動する</span>
          </div>


        <%# すずのアイコン %>
          <div class="dropdown">
            <div class="btn" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-bell ms-2" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
              <% if @supplier_notifications.present? %>
                <span class="badge bg-danger">new</span>
              <% end %>
            </div>
            <ul class="dropdown-menu dropdown-menu-end ps-3" aria-labelledby="dropdownMenuButton">
            <% if @supplier_notifications.present? %>
              <% @supplier_notifications.each do |notification| %>
                <% if notification.notification_type == "message" %>
                  <li><%= link_to "#{notification.user.family_name}さんからメッセージが届きました", supplier_chats_path, class: "dropdown-item me-4"%></li>
                <% elsif notification.notification_type == "entry" %>
                  <li><%= link_to "#{notification.user.family_name}さんからエントリーが届きました", new_supplier_chat_path, class: "dropdown-item me-4"%></li>
                <% end %>
              <% end %>
            <% else %>
              <li><a class="dropdown-item me-3" href="#">現在通知はありません</a></li>
            <% end %>
            </ul>
          </div>

        <%# 人のアイコン %>
            <div class="balloonoya">
              <%= link_to(company_details_supplier_company_path(current_supplier.id))  do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle mx-3 text-dark" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
              <% end %>
              <span class="balloon text-center">企業ページへ</span>
            </div>

            <%# ここからは右上のユーザーネームのドロップボタン %>
        <div class="dropdown">
            <button class="btn mx-2 px-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <%# （ ↪︎ idの「dropdown-toggle」を消すとドロップボックスの矢印が消える） %>
            
                <%# ユーザーネームと画像を表示させる %>
              <%= current_supplier.company_name%><%= image_tag current_supplier.company_image, class: 'rounded-circle ms-3', :size =>'55x55'%>
            </button>
                <%# ドロップボタンのリスト %>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
              <li><%= link_to 'ログアウト', destroy_supplier_session_path, method: :delete, class: " dropdown-item btn btn-outline-success text-center ms-2" %></li>
            </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<%# 会社一覧の検索部分のビュー %>
<div class="mb-3 ">
  <label for="exampleFormControlInput1" class="form-label"> 
  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search mx-3 my-2" viewBox="0 0 16 16">
  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
  </svg>検索条件</label>
</div>

<%= form_with url: search_companies_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword, class:"form-control border border-primary rounded my-2", placeholder:'キーワード検索', value: @keyword %>

  <%= f.collection_select(:area, Prefecture.all, :id, :name, {selected: @area}, {class:"select-box border border-primary rounded my-3", id:"item-prefecture", style:"width: 100%;"})%>

  <select name="[genre]" class="form-select border border-primary rounded my-2" aria-label="Default select example">
    <option value="">ジャンル</option>
    <% Company::INGREDIENTS_MAP.keys.each do |key| %>
      <optgroup label="<%= key %>">
        <% Company::INGREDIENTS_MAP[key].each do |value| %>
          <option value="<%= value %>" <%= @genre == value ? 'selected' : '' %>><%= value %></option>
        <% end %>
      </optgroup>
    <% end %>
  </select>

  <%= f.submit "検索する", class:"btn btn-primary float-end my-3" %>
<% end %>