config/routes.rb
Rails.application.routes.draw do
  devise_for :suppliers, controllers: {
    sessions: 'suppliers/sessions',
    passwords: 'suppliers/passwords',
    registrations: 'suppliers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  root 'companies#top'

  resources :users, only: :show
  resources :profiles, only: %i[new create edit update]
  resources :careers, only: %i[new create edit update destroy]

  resources :chats, only: %i[index new create show] do
    resources :messages, only: %i[new create]
  end

  namespace :supplier do
    resources :supplier_question_answers, only: %i[new create]
    resources :image_other_companies, only: %i[new create]
    resources :supplier_notifications, only: %i[index]
    resources :chats, only: %i[index new create show] do
      resources :messages, only: %i[new create]
    end

    resources :companies, only: %i[index create show edit update] do
      collection do
        get 'first_step'
        get 'second_step'
        get 'third_step'
        get 'fourth_step'
        get 'fifth_step'
        get 'sixth_step'
        get 'double_check'
      end

      member do
        get 'company_details'
        get 'ingredients_edit'
        get 'ingredients_update'
      end
    end
  end

  resources :user_question_answers, only: [:show] do
    collection do
      get 'question_description'
      get 'choice_questions'
      post 'answer_choice_questions'
      get 'scale_questions'
      post 'scale_choice_questions'
      get 'thinker'
      get 'pasi'
      get 'hamo'
      get 'ima'
      get 'revel'
      get 'pro'
    end
  end

  resources :companies, only: %i[index show] do
    resource :favorites, only: %i[show create destroy]
    resource :entries, only: %i[new create destroy]
    collection do
      get 'top'
      get 'search'
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :supplier
  has_many :favorites
  has_many :users, through: :favorites

  INGREDIENTS_MAP = {
    '営業': %w[個人営業 法人営業 ルート営業 テレフォンアポインター 営業アシスタント],
    'コーポレート': %w[一般事務 人事 経理 財務 法務 経営企画 秘書],
    '販売・サービス': ['販売・接客', '店長(ファッション)', 'ホールスタッフ', '調理', '店長(飲食)'],
    'コンサルティング': %w[経営コンサルティング 人事コンサルティング ITコンサルティング マーケティングコンサルティング キャリアコンサルティング],
    '教育': ['保育士・幼稚園教諭', 'スクール運営・マネジメント', '教師', '講師', 'スポーツインストラクター', '教務事務'],
    'エンジニア': %w[モバイルエンジニア webエンジニア インフラエンジニア システムエンジニア データサイエンティストグラフィック],
    'デザイナー': %w[デザイナー アートデザイナー クリエイティブデザイナー フォトグラファー 動画クリエイター イラストレーター]

  }

  # 引数を受け取るように設定
  def already_favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 引数を受け取るように設定
  def already_entries?(user)
    supplier.entries.where(user_id: user.id).exists?
  end

  def self.keyword(keyword)
    where([
            'company_content like? OR company_purpose like? OR company_environment like? OR ingredients like?', "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"
          ])
  end

  def self.genre(genre)
    where(['ingredients like ?', "%#{genre}%"])
  end

  def self.area(area)
    where(prefecture_id: area)
  end

  # ビュー数獲得のための記述
  is_impressionable

  with_options presence: true do
    validates :prefecture_id
    validates :founding_date
    validates :phone_number
    validates :company_url
    validates :company_content
    validates :company_purpose
    validates :company_environment
    validates :ingredients
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  impressionist actions: [:show]

  def top; end

  def index
    @company_topimage = Company.find(1)
    @company_images = Company.where.not(id: 1)
    if current_user
      @companies = Company.joins(:supplier).order("abs(suppliers.personality_score - #{current_user.personality_score})").page(params[:page]).per(5)
    else
      @companies = Company.all.page(params[:page]).per(5)
    end  
  end

  def show
    @company = Company.find(params[:id])
    @ingredients = JSON.parse(@company.ingredients)
    @other_images = @company.supplier.image_other_companies
    impressionist(@company, nil, unique: [:session_hash])
  end

  def search
    @keyword = params[:keyword]
    @area = params[:area]
    @genre = params[:genre]
    @companies = Company.all
    @companies = @companies.keyword(params[:keyword]) if params[:keyword] != ''
    @companies = @companies.area(params[:area]) if params[:area] != '0'
    @companies = @companies.genre(params[:genre]) if params[:genre] != ''
  end
end

app/controllers/supplier/companies_controller.rb
class Supplier::CompaniesController < ApplicationController
  before_action :authenticate_supplier!, except: %i[first_step]
  before_action :set_company_find, only: %i[edit update company_details ingredients_edit ingredients_update]
  before_action :set_company_new, only: %i[second_step third_step fourth_step fifth_step sixth_step double_check]
  before_action :move_to_index, only: %i[company_details edit update]

  def first_step; end

  def second_step; end

  def third_step
    session[:prefecture_id] = company_params[:prefecture_id]
    session['founding_date(1i)'] = params[:company]['founding_date(1i)']
    session['founding_date(2i)'] = params[:company]['founding_date(2i)']
    session['founding_date(3i)'] = params[:company]['founding_date(3i)']
    session[:phone_number] = company_params[:phone_number]
    session[:company_url] = company_params[:company_url]
  end

  def fourth_step
    session[:company_content] = company_params[:company_content]
  end

  def fifth_step
    session[:company_purpose] = company_params[:company_purpose]
  end

  def sixth_step
    session[:company_environment] = company_params[:company_environment]
  end

  def double_check
    session[:ingredients] = company_params[:ingredients]
    @check = Company.new(
      prefecture_id: session[:prefecture_id],
      founding_date: "#{session['founding_date(1i)']}-#{session['founding_date(2i)']}-#{session['founding_date(3i)']}",
      phone_number: session[:phone_number],
      company_url: session[:company_url],
      company_content: session[:company_content],
      company_purpose: session[:company_purpose],
      company_environment: session[:company_environment],
      ingredients: session[:ingredients]
    )
  end

  def create
    @company = Company.new(
      prefecture_id: session[:prefecture_id],
      founding_date: "#{session['founding_date(1i)']}-#{session['founding_date(2i)']}-#{session['founding_date(3i)']}",
      phone_number: session[:phone_number],
      company_url: session[:company_url],
      company_content: session[:company_content],
      company_purpose: session[:company_purpose],
      company_environment: session[:company_environment],
      ingredients: session[:ingredients],
      supplier_id: current_supplier.id
    )
    if @company.save
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'sixth_step'
    end
  end

  # 企業側のユーザーページ
  def company_details
    @favorites = Favorite.where(company_id: current_supplier.id).count
    @entries = Entry.where(supplier_id: current_supplier.id).count
    @ingredients = JSON.parse(@company.ingredients)
    @other_images = @company.supplier.image_other_companies

    @supplier_answer = current_supplier.supplier_question_answers
    @total = { 'hamo' => 0, 'pasi' => 0, 'revel' => 0, 'thinker' => 0, 'ima' => 0, 'pro' => 0 }
    @supplier_answer.each do |answer|
      @total[answer.personality_type] += answer.point
    end
  end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'edit'
    end
  end

  def ingredients_edit; end

  def ingredients_update
    if @company.update_attributes(ingredients_params)
      redirect_to company_details_supplier_company_path(@company.id)
    else
      render 'ingredients_edit'
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :prefecture_id,
      :founding_date,
      :phone_number,
      :company_url,
      :company_content,
      :company_purpose,
      :company_environment,
      ingredients: []
    ).merge(supplier_id: current_supplier.id)
  end

  def ingredients_params
    params.require(:company).permit(ingredients: [])
  end

  def set_company_new
    @company = Company.new
  end

  def set_company_find
    @company = Company.find(params[:id])
  end

  def move_to_index
    return redirect_to root_path if current_supplier.id != @company.supplier.id
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def third_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社のサービスは、どのような実績をあげていますか？
    ・プロダクトの強みとして、自慢できるポイントはなんですか？
    ・あなたの会社は、これからどのような展開をしていきますか？
    EOS
  end

  def fourth_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社が理想として掲げる理念はなんですか？
    ・企業活動を通して果たすべき使命（ミッション）はありますか？
    ・どのような志を持つ方を仲間に入れたいですか？
    EOS
  end

  def fifth_step_placeholder
    <<-"EOS".strip_heredoc
    ・あなたの会社では、どのような行動指針を大切にしていますか？
    ・チーム、職場はどのような雰囲気ですか？
    ・企業文化を支える、ユニークな制度はありますか？
    EOS
  end
end

app/views/companies/fifth_step.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を登録する 〜</h1>
    <%= form_with model: @company, url: sixth_step_companies_path, method: :get, local: true do |f|%>
      <div class="fs-1 text-secondary mb-3">5/6</div>
      <div class="fs-3">チームの文化や働く環境について書く</div>
      <%= f.text_area :company_environment, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:fifth_step_placeholder %>
      <%= f.submit "次へ" ,class:"btn btn-primary float-end mb-5" %>
    <% end %>
  </div>
</div>

app/views/companies/fourth_step.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を登録する 〜</h1>
    <%= form_with model: @company, url: fifth_step_companies_path, method: :get, local: true do |f|%>
      <div class="fs-1 text-secondary mb-3">4/6</div>
      <div class="fs-3">あなたの事業の目的について書く</div>
      <%= f.text_area :company_purpose, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:fourth_step_placeholder %>
      <%= f.submit "次へ" ,class:"btn btn-primary float-end mb-5" %>
    <% end %>
  </div>
</div>

app/views/companies/index.html.erb
  <% if user_signed_in? %>
    <%= render "shared/header_signin"%>
  <% elsif supplier_signed_in? %>
    <%= render "shared/header_supplier_signin"%>
  <% else %>
    <%= render "shared/header"%>
  <% end %>


<%# 画像のスライド %>
    <div class="slider_top mt-3 mb-5">
      <% @company_images.limit(3).each do |company_image| %>
        <div>
          <%= link_to(company_path(company_image.id), class: "text-decoration-none") do %>
            <%= image_tag company_image.supplier.company_image, :size =>'900x400'%>
            <p class="fs-2 text-center mt-2 text-dark"><%= company_image.supplier.company_name %></p>
          <% end %>
        </div>
      <% end %>
    </div>
<%# 画像のスライドショー %>

<%# 検索ページ %>
  <div class="container company_list">
    <div class="row">
        <%# 検索ページ %>
        <div class="col-3">
        <%= render "shared/search"%>
        </div>

        <%# 会社一覧 %>
        <div class="col-8 ms-5">
          <h4 style="text-align: center;">おすすめ企業一覧</h4>
          <%= render partial: 'company', collection: @companies %>
          <%= paginate @companies %>
        </div>
    </div>
  </div>

  <%= render "shared/footer"%>

app/views/companies/third_step.html.erb
<div class="new_base">
  <div class="new_inbase ">
   <h1 class="appname" >Work,LiveShift</h1>
   <h1 class="user_title mb-5" >〜 企業情報を登録する 〜</h1>
    <%= form_with model: @company, url: fourth_step_companies_path, method: :get, local: true do |f|%>
      <div class="fs-1 text-secondary mb-3">3/6</div>
      <div class="fs-3">あなたの会社の事業内容について書く</div>
      <%= f.text_area :company_content, class:"form-control border border-primary rounded my-3", id:"floatingInput",rows: 7, placeholder:third_step_placeholder%>
      <%= f.submit "次へ" ,class:"btn btn-primary float-end mb-5" %>
    <% end %>
  </div>
</div>

app/views/companies/top.html.erb
<div class="card bg-dark text-white">
  <%= image_tag 'blue_00004', class: 'card-img-top bg-dark' , :size =>'0x400'%>
    <div class="card-img-overlay">

          <%# トップページのヘッダーの画像部分 %>
        <nav class="navbar navbar-light">
          <div class="container-fluid" >
            <div class="navbar-brand"></div>
            <div class="d-flex ">

                 <%# ヘッダーのログインなどのリンク %>
              <% if user_signed_in? %>

                <div class="balloonoya">
                    <%= link_to(user_path(current_user.id), class: "d-flex justify-content-end d-flex align-items-center mt-1") do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle mx-3 text-white" viewBox="0 0 16 16">
                      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                      <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                      </svg>
                    <% end %>
                  <span class="balloon text-center text-dark">ユーザーページへ</span>
                </div>

                <%= link_to(destroy_user_session_path, method: :delete, class: "text-decoration-none")  do %>
                  <div class="border border-white rounded-pill btn-outline-success d-flex justify-content-end d-flex align-items-center mx-3 p-2">
                      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-check-fill text-white" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                      <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                      </svg>
                      <span class="text-white ms-2">ログアウト</span>
                  </div>
                <% end %>

              <% else %>

                <%= link_to(new_user_session_path, class: "text-decoration-none")  do %>
                  <div class="border border-white rounded-pill btn-outline-success d-flex justify-content-end d-flex align-items-center mx-3 p-2">
                      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-check-fill text-white" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                      <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                      </svg>
                      <span class="text-white ms-2">ログイン</span>
                  </div>
                <% end %>

                <%= link_to(new_user_registration_path, class: "text-decoration-none") do %>
                  <div class="border border-white rounded-pill btn-outline-success d-flex justify-content-end d-flex align-items-center mx-3 p-2">
                      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-plus-fill text-white" viewBox="0 0 16 16">
                      <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                      <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                      </svg>
                      <span class="text-white ms-2">新規登録</span>
                  </div>
                <% end %>
              <% end %>

            </div>
          </div>
        </nav>

          <%# 画像部分の文字 %>
        <div class="d-flex justify-content-center text-center mt-5">
          <div class="text-white fs-1 navbar-brand">
          Work,LiveShift
          <p class="text-white fs-5 mt-3">あなたに合った仕事が見つかる</p>
          </div>
        </div>
    </div>
  </div>



<div class="my-5 py-5 mx-auto" style="max-width: 80%;">
  <div class="row g-0">

    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title fs-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 18 18">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
          </svg>
          まずは企業を見てみる</h5>
        <p class="card-text pt-2">
        Work,LiveShift では様々な企業様に求人情報を掲載いただいております。<br>
        まずは、どのような企業があるのか確認してみましょう！
        </p>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card text-white  text-center">
        <%= image_tag 'cool', :size =>'100%x100%'%>
        <div class="card-img-overlay d-flex align-items-center d-flex justify-content-center">
          <%= link_to(companies_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image")  do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
              <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
            </svg>
            <span class="text-white  ms-2">人気の企業をみる</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="my-5 py-5 mx-auto border-top border-bottom border-secondary" style="max-width: 80%;">
  <div class="row g-0 my-5">

    <div class="col-md-6">
      <div class="card text-white  text-center">
        <%= image_tag 'human', :size =>'100%x100%'%>
        <div class="card-img-overlay d-flex align-items-center d-flex justify-content-center">
             <%# ログインの有無によりパスを変更 %>
          <% if user_signed_in? %>
              <%= link_to(companies_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image")  do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                  <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                </svg>
                <span class="text-white  ms-2">ユーザーとして始める</span>
              <% end %>
          <% else %>
              <%= link_to(new_user_registration_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image")  do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                  <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                </svg>
                <span class="text-white  ms-2">ユーザーとして始める</span>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title fs-4">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 20 20">
          <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
          <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
        </svg>
        ユーザーとして登録する</h5>
        <p class="card-text pt-2">
        ユーザーの皆様には、事前に36問のご質問に答えていただきます。<br>
        ご質問の回答を基に性格の分析をさせていただき、<br>
        あなたに合ったお仕事をご提案させていただきます。<br>
        全ての質問に正しい答えはありません。<br>
        リラックスした状態で、素直な自分自身についてご回答をお願いいたします。<br>
        </p>
      </div>
    </div>
  </div>
</div>


<div class="my-5 py-5 mx-auto" style="max-width: 80%;">
  <div class="row g-0">

    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title fs-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-building" viewBox="0 0 18 18">
            <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
            <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
          </svg>
          企業として登録する</h5>
        <p class="card-text pt-2">
        様々な業種、職種も掲載いただけます。<br>
        自社の想い、具体的な活動などを簡単にお伝えできるように<br>
        フォーマットもご準備させていただきます。<br>
        自社の魅力を多くの方に広げてるために、<br>
        Work,LiveShiftをご活用ください。
        </p>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="card text-white  text-center">
        <%= image_tag 'office', :size =>'100%x100%'%>
        <div class="card-img-overlay d-flex align-items-center d-flex justify-content-center">
          <% if supplier_signed_in? %>
            <%= link_to(company_details_supplier_company_path(current_supplier), class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image")  do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
              </svg>
              <span class="text-white  ms-2">企業情報を掲載する</span>
            <% end %>
          <% else %>
            <%= link_to(first_step_supplier_companies_path, class: "mouse_white border border-white rounded-pill text-white p-3 text-decoration-none top_image")  do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
              </svg>
              <span class="text-white  ms-2">企業情報を掲載する</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer"%>